language: ruby
bundler_args: --without development production staging
rvm:
  - 2.2.3
addons:
  postgresql: 9.3
before_script:
  - psql -c 'create database ort_test' -U postgres
  - cp config/database.yml.example config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
