language: ruby
bundler_args: --without development production

addons:
  postgresql: 9.4

env:
  - RAILS_ENV=test PG_HOST=localhost PG_USERNAME=postgres

before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate

notifications:
  slack: wcmc:s9u7NNtJZuCORuIABQ1G4KPb
