version: '3'
services:
  rails:
    container_name: ors-rails
    build:
      dockerfile: Dockerfile
    command: rm -rf /railsapp/tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'
    volumes:
      - '.:/railsapp'
      - ors_bundler_gems:/usr/local/bundle
    ports:
      - '3000:3000'
    networks:
      - ors
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - db
    environment:
      SUS_ORS_DATABASE_HOST: ors-db
      SUS_ORS_SIDEKIQ_REDIS_URL: redis://ors-redis:6379/0
      ALLOWED_HOST: ors-rails

  db:
    container_name: ors-db
    image: postgres:9.4
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - 'ors_pgdata:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    networks:
      - ors
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "ors_development"

  redis:
    container_name: ors-redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ors
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ors_redis_data:/data

  # sidekiq:
  #   container_name: ors-sidekiq
  #   build:
  #     context: ./rails-api
  #     dockerfile: Dockerfile
  #   networks:
  #     - ors
  #   depends_on:
  #     - db
  #     - redis
  #   command: /bin/bash -l -c "bundle exec sidekiq -C config/sidekiq.yml"
  #   volumes:
  #     - './rails-api:/railsapp'
  #     - ors_bundler_gems:/usr/local/bundle
  #   environment:
  #     ORS_DATABASE_HOST: ors-db
  #     ORS_SIDEKIQ_REDIS_URL: redis://ors-redis:6379/0

networks:
  ors:
    driver: bridge

volumes:
  ors_pgdata:
  ors_node_modules:
  ors_redis_data:
  ors_bundler_gems:
