version: '3'
services:
  rails:
    container_name: ors-rails
    build:
      dockerfile: Dockerfile
    command: /bin/bash -l -c "rm -f /railsapp/tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/railsapp'
      - ors_bundler_gems:/usr/local/bundle
      # - ~/.ssh:/root/.ssh:ro
    ports:
      - '${ORS_CONTAINER_RAILS_PORT:-3000}:3000'
    networks:
      - ors
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - db
      - mailcatcher
    environment:
      REDIS_URL: redis://ors-redis:6379/0
      ORS_SMTP_ADDRESS: ors-mailcatcher

  db:
    container_name: ors-db
    image: postgres:9.4
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - 'ors_pgdata:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    networks:
      - ors
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "ort_development"

  redis:
    container_name: ors-redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ors
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ors_redis_data:/data

  sidekiq:
    container_name: ors-sidekiq
    build:
      dockerfile: Dockerfile
    networks:
      - ors
    depends_on:
      - db
      - redis
      - mailcatcher
    command: /bin/bash -l -c "mkdir -p /tmp/pids && bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - '.:/railsapp'
      - ors_bundler_gems:/usr/local/bundle
    environment:
      REDIS_URL: redis://ors-redis:6379/0
      ORS_SMTP_ADDRESS: ors-mailcatcher

  mailcatcher:
    container_name: ors-mailcatcher
    image: sj26/mailcatcher
    ports:
      - '${ORS_CONTAINER_MAILCATCHER_PORT:-1080}:1080'
    networks:
      - ors

networks:
  ors:
    driver: bridge

volumes:
  ors_pgdata:
  ors_node_modules:
  ors_redis_data:
  ors_bundler_gems:
