version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ors
      - ors-bundler_gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:9.4
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432"
    volumes:
      - ors-pgdatadb:/var/lib/postgresql/data
      - ./entrypoints/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
 
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379"
    volumes:
      - ors-redis:/data
  
  sidekiq:
     build: .
     volumes:
       - .:/ors
     links:
       - db
       - redis
     command: bash -c "bundle exec sidekiq"
     environment:
       REDIS_URL: redis://redis:6379/1

volumes:
  ors-pgdatadb:
  ors-bundler_gems:
  ors-redis:
