default: &default
  admin_pwd: "admin"

development:
  <<: *default
  secret_key_base: cb874357ceef54e600faa840a73354486d4d302aac1ffe3d7974f186bed29a1f29e5dabd10c1b0704835779c1a7d6e29491681ff8b014c8526035b2ad2e197b9
  redis:
    namespace: <%= ENV["REDIS_NAMESPACE_KEY"] || "ORS" %>
    url: <%= ENV["REDIS_URL"] || "redis://127.0.0.1:6379/1" %>
  instiki_url: <%= ENV["INSTIKI_URL"] || "http://instiki.unepwcmc-008.vm.brightbox.net" %>
  mailer:
    host: 'localhost:3000'

test:
  <<: *default
  secret_key_base: aabb7e5e19c640a94ffd75312abc43868dc97096ca22b86af575967fe4ce54ff4021d7c3a7bcfd70dc62197e10391bd8f556b2d6d1dd6faf92703b6b4e8c946c
  redis:
    namespace: <%= ENV["REDIS_NAMESPACE_KEY"] || "ORS" %>
    url: <%= ENV["REDIS_URL"] || "redis://127.0.0.1:6379/1" %>
  instiki_url: <%= ENV["INSTIKI_URL"] || "http://instiki.unepwcmc-008.vm.brightbox.net" %>
  mailer:
    host: 'localhost:3000'

staging_and_production: &defaults
  admin_pwd: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  exception_notification_email: <%= ENV["EXCEPTION_NOTIFICATION_EMAIL"] %>
  exception_notification_slack_webhook: <%= ENV["EXCEPTION_NOTIFICATION_SLACK_WEBHOOK"] %>
  new_relic_license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>

  mailer:
    address: <%= ENV["MAILER_ADDRESS_KEY"] || "" %>
    port: <%= ENV["MAILER_PORT_KEY"] || "" %>
    domain: <%= ENV["MAILER_DOMAIN_KEY"] || "" %>
    username: <%= ENV["MAILER_USERNAME_KEY"] || "" %>
    password: <%= ENV["MAILER_PASSWORD_KEY"] || "" %>
    asset_host: <%= ENV["MAILER_ASSET_HOST_KEY"] || "" %>
    host: <%= ENV["MAILER_HOST_KEY"] || "" %>
  redis:
    namespace: <%= ENV["REDIS_NAMESPACE"] || "ORS" %>
    url: <%= ENV["REDIS_URL"] || "redis://127.0.0.1:6379/1" %>
  instiki_url: <%= ENV["INSTIKI_URL"] || "http://instiki.unepwcmc-008.vm.brightbox.net" %>

production:
  <<: *defaults

staging:
  <<: *defaults
